name: 北京大学手风琴协会
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://pku-accordion.github.io/
paginate_path: "blog/page:num/"
permalink: blog/:title/

paginate_path: "webvideos/page:num/"
permalink: webvideos/:title/

markdown: redcarpet
pygments: true
paginate: 5

navigation:
 - title: 最新动态
   url: /index.html
 - title: 协会简介
   url: /about
 - title: 联系我们
   url: /contact